### ISSUE TITLE
docker版本可以更改端口吗？

### ISSUE THREAD

**Issue by wander555** [caryyu/douban-openapi-server#15]
5000和群晖的默认端口冲突了，可以自定义端口吗？

**Comment by banjuer** [comment]
> 5000和群晖的默认端口冲突了，可以自定义端口吗？

可以的， -p 8500:5000  api指定的时候就是http://192.xx.x.x:8500

**Comment by wander555** [comment]
感谢回复!
使用多了以后,IP被标记异常,是不是只能换selenium了?

<img width="943" alt="image" src="https://user-images.githubusercontent.com/6134211/154793403-04f69333-9228-46bc-ba37-5ec32456117f.png">

**Comment by caryyu** [comment]
@wander555 这个是豆瓣限流检测导致，家庭 NAT 网络一般等待几个小时会自动解封。

**Comment by neillee1991** [comment]
Docker端口做了映射8082:5000，
直接在浏览器地址输入http://192.168.50.100:8082/movies?type=partial&q=Harry%20Potter
返回的是"Results Not Found: Harry Potter"
这正常么？

**Comment by caryyu** [comment]
> Docker端口做了映射8082:5000， 直接在浏览器地址输入http://192.168.50.100:8082/movies?type=partial&q=Harry%20Potter 返回的是"Results Not Found: Harry Potter" 这正常么？

@neillee1991  非常感谢你的反馈与测试，目前我开了一个新 Issue 进行跟踪该问题：https://github.com/caryyu/douban-openapi-server/issues/16

**Comment by yefoenix** [comment]
同求改一下默认端口，因为我用的猫盘+黑群晖，Docker 只能用Host网络，做不了端口映射，只能使用容器默认端口。

**Comment by caryyu** [comment]
@yefoenix 谢谢你的反馈，对于 Host 网络而言确实 `-p` 参数无法解决上述的问题，我这边能够想到的解决方案就是把 ENTRYPOINT 中的参数放入 CMD 中。

**Comment by caryyu** [comment]
@yefoenix 本地 host 网络端口问题已经解决，你可以参考下述方式进行设置：

> docker run --rm -d --host caryyu/douban-openapi-server:latest -b 0.0.0.0:6000 app:app

我先关闭该 Issue 了，有任何问题请重开，谢谢。
