### ISSUE TITLE
搜索不到sid，不管是中文还是原名都出错

### ISSUE THREAD

**Issue by 1294266616** [caryyu/douban-openapi-server#4]
[18:09:41] [WRN] [29] Jellyfin.Plugin.OpenDouban.ImageProvider: [DOUBAN] Got images failed because the sid of "占领2" is empty!
#

**Comment by 1294266616** [comment]
服务端日志
[2021-06-08 16:37:13 +0000] [1] [INFO] Starting gunicorn 20.1.0
,[2021-06-08 16:37:13 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
,[2021-06-08 16:37:13 +0000] [1] [INFO] Using worker: sync
,[2021-06-08 16:37:13 +0000] [10] [INFO] Booting worker with pid: 10
,[2021-06-08 16:37:13 +0000] [11] [INFO] Booting worker with pid: 11
,[2021-06-08 16:37:13 +0000] [12] [INFO] Booting worker with pid: 12
,[2021-06-08 16:49:53 +0000] [1] [INFO] Handling signal: winch
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E9%AD%94%E7%81%B5
,'NoneType' object is not subscriptable
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E7%8B%BC%E8%A1%8C%E8%80%85
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=The.Man.Standing.Next.2020.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E4%BA%BA%E4%B9%8B%E6%80%92.Wrath.of.Man.2021.2160p.WEB-DL.DDP5.1.HDR.H265-%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E8%87%B4%E5%91%BD%E5%BC%AF%E9%81%936%EF%BC%9A%E7%BB%88%E6%9E%81%E5%AE%A1%E5%88%A4
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E8%87%B4%E5%91%BD%E5%BC%AF%E9%81%935%EF%BC%9A%E8%A1%80%E6%97%8F
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E8%87%B4%E5%91%BD%E5%BC%AF%E9%81%93
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E8%87%B4%E5%91%BD%E5%BC%AF%E9%81%934%EF%BC%9A%E8%A1%80%E8%85%A5%E8%B5%B7%E6%BA%90
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E6%88%91%E7%9A%84%E5%A7%90%E5%A7%90.Sister.2021.1080P.WEB-DL.X264.AAC-Vampire
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E8%87%B4%E5%91%BD%E5%BC%AF%E9%81%933
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E8%87%B4%E5%91%BD%E5%BC%AF%E9%81%932
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E8%87%B4%E5%91%BD%E5%BC%AF%E9%81%93
,'NoneType' object is not subscriptable
,'NoneType' object is not subscriptable
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E8%87%B4%E5%91%BD%E5%BC%AF%E9%81%936%EF%BC%9A%E7%BB%88%E6%9E%81%E5%AE%A1%E5%88%A4
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E8%87%B4%E5%91%BD%E5%BC%AF%E9%81%934%EF%BC%9A%E8%A1%80%E8%85%A5%E8%B5%B7%E6%BA%90
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=The.Man.Standing.Next.2020.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E8%87%B4%E5%91%BD%E5%BC%AF%E9%81%933
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E8%87%B4%E5%91%BD%E5%BC%AF%E9%81%932
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E8%87%B4%E5%91%BD%E5%BC%AF%E9%81%93
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E4%BA%BA%E4%B9%8B%E6%80%92.Wrath.of.Man.2021.2160p.WEB-DL.DDP5.1.HDR.H265-%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95
,403 Client Error: Forbidden for url: https://www.douban.com/search?q=%E6%88%91%E7%9A%84%E5%A7%90%E5%A7%90.Sister.2021.1080P.WEB-DL.X264.AAC-Vampire
,'NoneType' object is not subscriptable
,

**Comment by caryyu** [comment]
你的 NAT 出网被豆瓣禁了。

**Comment by 1294266616** [comment]
> 你的 NAT 出网被豆瓣禁了。

重新试了下还是不能搜索到，另一个豆瓣的可以搜到了

[05:13:14] [INF] [30] Jellyfin.Plugin.OpenDouban.ImageProvider: [DOUBAN] GetImages for item: 人之怒
,[05:14:06] [INF] [31] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Finished Library Sync Taking 00:00:00.0124457
,[05:13:14] [WRN] [30] Jellyfin.Plugin.OpenDouban.ImageProvider: [DOUBAN] Got images failed because the sid of "人之怒" is empty!
,[05:13:20] [INF] [27] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Starting Library Sync...
,[05:14:00] [INF] [31] Jellyfin.Plugin.Douban.MovieProvider: [DOUBAN] Getting metadata for "人之怒.Wrath.of.Man.2021.2160p.WEB-DL.DDP5.1.HDR.H265-中文字幕"
,[05:13:20] [INF] [27] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Finished Library Sync Taking 00:00:00.0140001
,[05:13:20] [INF] [27] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Removed 0 items:  
,[05:13:20] [INF] [27] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Updated 1 items:  3f6a0e74931da5c65ff738183b952adf
,[05:13:20] [INF] [27] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Added 0 items:  
,[05:14:00] [INF] [31] Jellyfin.Plugin.Douban.MovieProvider: Start to GetSubject by Id: 27046740
,[05:14:00] [INF] [31] Jellyfin.Plugin.Douban.MovieProvider: Frodo request URL: https://frodo.douban.com/api/v2/movie/27046740?_ts=1623215640&_sig=3LsCS2ezX6NCtc0C0wTnFyVBJbw%3d&apikey=0dad551ec0f84ed02907ff5c42e8ec70
,[05:14:01] [INF] [28] Jellyfin.Plugin.Douban.MovieProvider: [DOUBAN] Get the metadata of "人之怒.Wrath.of.Man.2021.2160p.WEB-DL.DDP5.1.HDR.H265-中文字幕" successfully!
,[05:14:01] [INF] [28] Jellyfin.Plugin.Douban.ImageProvider: [DOUBAN] GetImages for item: 人之怒
,[05:14:01] [INF] [28] Jellyfin.Plugin.Douban.ImageProvider: Start to GetSubject by Id: 27046740
,[05:14:01] [INF] [28] Jellyfin.Plugin.Douban.ImageProvider: Frodo request URL: https://frodo.douban.com/api/v2/movie/27046740?_ts=1623215641&_sig=ECeB%2fIvcTiPFfapcTYNHaH%2fTimM%3d&apikey=0dad551ec0f84ed02907ff5c42e8ec70
,[05:14:06] [INF] [31] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Starting Library Sync...
,[05:14:06] [INF] [31] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Added 0 items:  
,[05:14:06] [INF] [31] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Updated 1 items:  3f6a0e74931da5c65ff738183b952adf
,[05:14:06] [INF] [31] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: "LIBRARYSYNC" Removed 0 items:

**Comment by caryyu** [comment]
因为两种机制不同，因为该项目目前采用访问 https://movie.douban.com 进行爬虫的机制来实现的，如果 `Jellyfin.Plugin.Douban` 这个插件能够满足你的要求，你就先用原作者的吧。

**Comment by caryyu** [comment]
Due to the PR had been stale for 2 days,  I decided to close it, Please re-issue if any questions are out there
